require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = '*_spec.rb'
  t.verbose = false
end

task :default => [:spec, :benchmark]

task :benchmark do |t|
  eval File.read './benchmark.rb'
end
